<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE books[<!ELEMENT books (book+)>
<!ELEMENT book (title,author,pages,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>
<books>
<book>
 <title> Web Technologies </title>
 <author>A.Ramesh</author>
 <pages>1200</pages>
 <price>2552.75</price>
</book>
<book>
 <title> Operating Systems </title>
 <author>Galvin</author>
 <pages>900</pages>
 <price>850.50</price>
</book>
</books>